/* Generated by: awk -f usage_page.awk usb_hid_usages */

const char *usage_page(int i);

const char *
usage_page(int i)
{
	switch(i) {
	case 1:
		return("Generic Desktop");
	case 2:
		return("Simulation Controls");
	case 3:
		return("VR Controls");
	case 4:
		return("Sports Controls");
	case 5:
		return("Game Controls");
	case 6:
		return("Generic Device Control");
	case 7:
		return("Keyboard");
	case 8:
		return("LEDs");
	case 9:
		return("Button");
	case 10:
		return("Ordinal");
	case 11:
		return("Telephony");
	case 12:
		return("Consumer");
	case 13:
		return("Digitizer");
	case 15:
		return("Physical Interface Device");
	case 16:
		return("Unicode");
	case 20:
		return("Alphnumeric Display");
	case 64:
		return("Medical Instrument");
	case 128:
		return("Monitor");
	case 129:
		return("Monitor Enumerated Values");
	case 130:
		return("VESA Virtual Controls");
	case 132:
		return("Power Device");
	case 133:
		return("Battery System");
	case 140:
		return("Bar Code Scanner");
	case 141:
		return("Weighing Device");
	case 142:
		return("Magnetic Stripe Reader");
	case 144:
		return("Camera Control");
	case 145:
		return("Arcade Device");
	case 0xFF00:
		return("Microsoft");
	default:
		return("Unknown Page");
	}
}
